spring:  datasource:    driverClassName: com.mysql.cj.jdbc.Driver    url: jdbc:mysql://localhost:3306/jeep    username: jeep    password: jeep  



logging:
  level:
    root: warn
    '[com.blorferind]': debug